### ISSUE TITLE
Init modes

### ISSUE THREAD

**Issue by ns-phennessy** [ns-phennessy/Bolt#18]
Want to have ability to do `shell` or `daemon` modes
### Shell Mode

Would allow one to use the terminal to connect and have an interactive shell, but also do bot level things using `/command`, so I could easily manage plugins and other things
### Daemon Mode

Will start the bot, load all the plugins, and then create a daemon process. This will just run and do everything from the chat room instead of the terminal

**Comment by ZetaHunter** [comment]
Perhaps we could use http://click.pocoo.org/5/ for easier interface writing? `./bot.py --debug --daemon`
While at it add optional arguments that current config has.

**Comment by ns-phennessy** [comment]
Closing in favor of https://github.com/ns-phennessy/Bolt/issues/75
